<?php

/*
| In-app guide topics (shared with the prototype's Ask Dopay assistant).
| keywords: lower-case words or phrases that match a question.
*/

return [
    ['title' => 'Taxes: VAT, returns and tax payments', 'keywords' => ['tax', 'taxes', 'vat', 'tva', 'vat return', 'tax return', 'remit', 'remittance', 'paye', 'withholding', 'tax rate', 'tax payment', 'filing', 'filing day', 'ura', 'firs'], 'answer' => 'Open <b>Billing → Taxes</b> and pick a country. Each month shows the VAT/TVA <b>charged</b> on approved invoices, the amount <b>remitted</b>, the <b>balance</b> and the due date.<ul><li><b>Pay a return</b>: click <b>Record payment</b> on the month. It records a Tax-category expense for that period; it counts as remitted once another approver marks it paid.</li><li><b>PAYE, withholding and other taxes</b>: record them the same way, leaving the period blank.</li><li><b>Rates and filing days</b>: on the Taxes page (Settings permission). Issued invoices keep their rate.</li><li>The <b>invoice register</b> lists each invoice with the customer TIN; <b>Export CSV</b> downloads the monthly summary.</li></ul>', 'route' => 'taxes.index'],
    ['title' => 'Getting around Dopay', 'keywords' => ['getting started', 'overview', 'modules', 'menu', 'navigate', 'sidebar', 'what is dopay', 'start', 'tour', 'features'], 'answer' => 'Dopay keeps customers, billing, spending, finance forms and administration in one place:<ul><li><b>Dashboard</b> shows what needs attention today.</li><li><b>Billing</b>: Customers, Invoices, Payments, Receipts, Taxes.</li><li><b>Spending & forms</b>: Finance forms (Appendices A–K), Expenses, Suppliers.</li><li><b>Catalogue & records</b>: Products, Documents, Reports, Communications.</li><li><b>Administration</b>: Users & roles, Audit trail, Settings.</li></ul>Search anything from the bar at the top (press <b>/</b>), and switch branch or country from the selector next to it.', 'route' => 'dashboard'],
    ['title' => 'Finding any record fast', 'keywords' => ['search', 'find', 'look up', 'lookup', 'locate', 'shortcut'], 'answer' => 'Use the search bar at the top of every page (press <b>/</b> to jump to it). Type several words and Dopay matches them all, across customers, invoices, payments, receipts, statements, documents and finance forms. For example <i>John 250000</i> finds John Uganda Ltd’s UGX 250,000 payment and its receipt.'],
    ['title' => 'Switching branch, country and currency', 'keywords' => ['branch', 'switch branch', 'country', 'countries', 'consolidated', 'all branches', 'currency view', 'usd'], 'answer' => 'The branch selector at the top decides what you see. Pick a branch to work in its local currency, or <b>All branches · USD</b> for consolidated figures converted at the recorded exchange rates. Local roles (accountants, country managers) are placed in their own branch automatically; the Financial Controller, Regional Manager, CFO and CEO see all countries.'],
    ['title' => 'Adding a customer or member', 'keywords' => ['add customer', 'new customer', 'add a customer', 'customer', 'customers', 'register customer', 'member', 'customer profile', 'edit customer', 'credit limit'], 'answer' => 'Go to <b>Billing → Customers</b> and press <b>New customer</b> (or use the quick action on the Dashboard). Choose the branch; country, currency and tax follow from it. Once saved, the customer’s details fill every invoice, receipt and statement automatically. Changing a credit limit is logged in the audit trail.', 'route' => 'customers.index'],
    ['title' => 'Creating an invoice', 'keywords' => ['create invoice', 'new invoice', 'make invoice', 'raise invoice', 'invoice builder', 'bill a customer', 'invoice'], 'answer' => '<ol><li>Press <b>New invoice</b> (Dashboard or Billing → Invoices).</li><li>Pick the customer: address, tax ID, currency and terms load by themselves.</li><li>Add products or custom lines; totals, discount and VAT calculate as you type, with a live preview.</li><li>Press <b>Submit for approval</b>. Once approved, <b>Generate official PDF</b>, then send it.</li></ol>The number (e.g. A4S-UG-INV-2026-000237) follows your country’s sequence.'],
    ['title' => 'Who approves invoices', 'keywords' => ['approve invoice', 'invoice approval', 'pending approval', 'approve', 'approval invoice', 'who approves', 'approves invoices', 'invoice approver', 'approve an invoice'], 'answer' => 'Invoices submitted by officers wait for a <b>Finance Manager</b>, <b>Branch Manager</b>, <b>Assistant/Country Manager</b>, <b>Financial Controller</b> or <b>CFO</b>. Approvers see them under <b>Invoices → Pending approval</b> and on the Dashboard. After approval, the preparer generates the official PDF.', 'route' => 'invoices.index'],
    ['title' => 'Sending an invoice, receipt or statement', 'keywords' => ['send invoice', 'share', 'send a receipt', 'send a statement', 'send an invoice', 'whatsapp', 'email invoice', 'telegram', 'imo', 'copy link', 'share link', 'send receipt', 'send statement'], 'answer' => 'Open the document and use <b>Send & share</b>: WhatsApp and Telegram open with the message and a secure link filled in; Email opens a pre-filled message with the PDF attached; IMO copies the message for pasting. Every send is saved to the customer’s timeline and the Communications log. Invoices unlock sharing once approved and generated.'],
    ['title' => 'Recording a payment', 'keywords' => ['record payment', 'record a payment', 'payment', 'paid', 'customer paid', 'receive money', 'mobile money', 'allocate', 'split payment', 'partial payment'], 'answer' => 'Press <b>Record payment</b>, choose the customer, enter amount, method and transaction reference, then <b>Auto-allocate oldest first</b> (or split it across invoices yourself). Saving updates the invoices’ balances and issues a receipt straight away. Anything not allocated stays as credit on the account.'],
    ['title' => 'Issuing receipts', 'keywords' => ['receipt', 'issue receipt', 'create receipt', 'reprint receipt'], 'answer' => 'Receipts are generated from recorded payments, so the amount and reference always match. Record the payment and the receipt opens ready to print or share. Past receipts are under <b>Billing → Receipts</b>.', 'route' => 'payments.index'],
    ['title' => 'Refunding or reversing a payment', 'keywords' => ['reverse', 'refund', 'reverse a payment', 'refund a payment', 'reversal', 'cancel payment', 'wrong payment'], 'answer' => 'In <b>Billing → Payments</b> press <b>Reverse</b> on the payment. It needs a reason and a second person’s authorization with their PIN. The invoice balance goes back up, the receipt is voided, and both stay in the audit trail; nothing is deleted.', 'route' => 'payments.index'],
    ['title' => 'Customer statements', 'keywords' => ['statement', 'account statement', 'balance', 'customer balance', 'statement of account'], 'answer' => 'Open the customer and choose the <b>Statement</b> tab. Pick a period (this month, last month, quarter, year) to see date, reference, debit, credit and running balance, then send it by WhatsApp, email or link.', 'route' => 'customers.index'],
    ['title' => 'Finance forms (Appendices A–K)', 'keywords' => ['finance forms', 'forms', 'appendix', 'appendices', 'fill online', 'template form', 'paper forms'], 'answer' => 'All your finance forms live in <b>Spending & forms → Finance forms</b>: Expense Memorandum (A), Petty Cash Voucher (B), Receipt Reimbursement Certification (C), Budgets (F), Branch Financial Report (G), Interbranch Transfer Memo (J) and Cash Advance Request (K). Press <b>Fill online</b>; the entity, currency and reference number fill in, the preview matches your printed template, and submitting starts the approval chain.', 'route' => 'forms.index'],
    ['title' => 'Expense Memorandum (Appendix A)', 'keywords' => ['expense memo', 'expense memorandum', 'memo', 'appendix a', 'request funds', 'approval route', 'regional manager route', 'cfo route'], 'answer' => '<ol><li>Finance forms → Expense Memorandum → <b>Fill online</b>.</li><li>Choose the approval route: <b>Regional Manager</b> (Template 1) or <b>CFO/CEO</b> (Template 2).</li><li>Add lines with category and amount, the payment details and the justification.</li><li>Attach receipts or link a Receipt Reimbursement Certification (required).</li><li>Submit. It needs all four signatures: Accountant/AM → CM or RM → Global Financial Controller → RM or CFO/CEO.</li></ol>When approved, <b>Mark as paid</b> posts each line to Expenses and budget monitoring.'],
    ['title' => 'Petty Cash Voucher (Appendix B)', 'keywords' => ['petty cash', 'voucher', 'impress', 'imprest', 'appendix b', 'float'], 'answer' => 'Finance forms → Petty Cash Voucher. Enter who was paid, the petty cash holder and the lines; amount in words is written for you. The holder signs “Paid by” and an Accountant or Branch Manager signs “Approved by” (the holder can never approve their own voucher). Link the Expense Memorandum that reimburses the float, then <b>Mark reimbursed</b>. Prints two vouchers per A4 sheet.'],
    ['title' => 'No receipt? Receipt Reimbursement Certification (Appendix C)', 'keywords' => ['no receipt', 'receipt reimbursement', 'certification', 'appendix c', 'lost receipt', 'without receipt'], 'answer' => 'When a vendor can’t give a receipt, fill <b>Receipt Reimbursement Certification</b>: the purchaser lists the payments and certifies them, then an Accountant or Assistant Manager approves. Once approved, <b>Use in a new expense memo</b> links it as the memo’s supporting document.'],
    ['title' => 'Budgets and budget monitoring (Appendix F)', 'keywords' => ['budget', 'budgets', 'annual budget', 'quarterly budget', 'monthly budget', 'budget monitoring', 'variance', 'actual vs budget', 'over budget', 'appendix f'], 'answer' => 'Prepare a <b>Monthly, Quarterly or Annual</b> budget in Finance forms → Expense Budget across the 21 A4S categories; the Financial Controller reviews it. <b>Budget monitoring</b> (card on the Finance forms page) compares the approved annual budget with actual spending by month or year to date. Actuals post automatically from paid expenses and memos; bars turn amber at 90% and red over 100%.', 'route' => 'budget.index'],
    ['title' => 'Branch Financial Report (Appendix G)', 'keywords' => ['branch financial report', 'financial report', 'bank reconciliation', 'reconcile', 'bank statement', 'appendix g', 'monthly report', '15th'], 'answer' => 'Finance forms → Branch Financial Report. Enter the month, bank and opening balance, then <b>Import from Dopay</b> to pull that month’s payments and paid expenses. Add the closing balance from the bank statement and attach the statement. You can only submit when the difference is zero. Due to HQ by the <b>15th of the following month</b>; it’s signed by the Accountant, CM/AM, Finance Manager and Financial Controller.'],
    ['title' => 'Interbranch funding (Appendix J)', 'keywords' => ['interbranch', 'intercompany', 'inter-branch', 'another branch pays', 'fund transfer', 'appendix j'], 'answer' => 'When one country pays another’s expenses, fill <b>Interbranch Transfer Memorandum</b>: choose the paying and receiving entity and pick approved memo references (description and amount fill in). The paying branch’s accountant acknowledges it and the Financial Controller notes it. Approved memos appear under <b>Intercompany payables</b> on the Finance forms page until you <b>Record repayment</b>.'],
    ['title' => 'Cash advances (Appendix K)', 'keywords' => ['cash advance', 'advance', 'appendix k', 'liquidation', 'liquidate', 'per diem', 'pocket money', 'customs clearing'], 'answer' => 'Fill <b>Cash Advance Request Form</b> with the purpose, amounts and expected date of use; the liquidation date is set to 5 working days after use (Policy 14.4). Five signatures: Accountant/AM → CM or RM → Financial Controller → CFO → CEO. After <b>Disburse advance</b>, record the liquidation with receipts; late ones are flagged on the Dashboard.'],
    ['title' => 'Signing and approving forms', 'keywords' => ['sign', 'signature', 'e-signature', 'who signs', 'signs', 'sign a form', 'approve form', 'my signature', 'awaiting my signature', 'queue', 'return form', 'reject', 'pin'], 'answer' => 'Forms waiting for you show on the Dashboard, in the sidebar badge and under <b>Finance forms → Awaiting my signature</b>. Open one, check the preview, press <b>Sign</b> and enter your PIN. Dopay stamps your name, date, local time and a signature ID. Use <b>Return</b> with a comment to send it back to the preparer. You can only sign steps that match your role and country.', 'route' => 'forms.index'],
    ['title' => 'Changing something already approved', 'keywords' => ['edit approved', 'revise', 'approved invoice', 'change an approved', 'already approved', 'edit an approved', 'change approved', 'void', 'cancel form', 'cancel invoice', 'authorization', 'authorize'], 'answer' => 'Approved invoices and forms can’t be edited silently. Use <b>Revise (authorized)</b> or <b>Edit</b> on the document: give a reason and a second approver’s PIN. The revision restarts the approval chain and the audit trail keeps the before and after. Cancelling or voiding works the same way; nothing is deleted.'],
    ['title' => 'Printing and downloading', 'keywords' => ['print', 'pdf', 'download', 'word', 'excel', 'docx', 'xlsx', 'export form', 'printout'], 'answer' => 'Every invoice, receipt and form has <b>Print</b> and <b>PDF</b>. Finance forms can also download as your original <b>Word or Excel</b> template, filled in. Forms print on A4 (budgets and branch reports in landscape; petty cash vouchers two per sheet), and signatures print with their date, time and signature ID. Reports export to PDF, Excel or CSV.'],
    ['title' => 'Expenses vs expense memos', 'keywords' => ['expense', 'expenses', 'new expense', 'spend', 'spending', 'supporting document', 'upload receipt', 'difference between', 'expenses and expense', 'expense module'], 'answer' => '<b>Expenses</b> is the ledger of what was spent (Draft → Submitted → Reviewed → Approved → Paid). A paid <b>Expense Memorandum</b> or liquidated cash advance posts its lines here automatically. For small items you can add an expense directly with <b>New expense</b> and attach the receipt.', 'route' => 'forms.index'],
    ['title' => 'Reference numbers', 'keywords' => ['reference number', 'ref no', 'numbering', 'invoice number format', 'sequence', 'ugd2026'], 'answer' => 'Numbers follow your templates per country: <b>UGD2026-A-017</b> (memo), <b>UGD-HQ-2026-B-004</b> (petty cash), <b>UGD-J-2026-012</b> (interbranch), <b>UGD2026-K-002</b> (cash advance), and A4S-UG-INV-2026-000237 for invoices. Change the patterns in <b>Settings → Documents</b>.'],
    ['title' => 'Exchange rates and currencies', 'keywords' => ['exchange rate', 'rates', 'currency', 'usd rate', 'convert', 'base currency'], 'answer' => 'Set units per 1 USD in <b>Settings → Finance</b>. Each transaction stores the rate on its date, so past invoices never change when you update rates. Consolidated reports use USD as the base currency.'],
    ['title' => 'Adding a country or branch', 'keywords' => ['add country', 'new country', 'add branch', 'new branch', 'kenya', 'expand', 'entity', 'add a country', 'add a branch', 'another country', 'new market', 'open a branch'], 'answer' => 'In <b>Settings → Countries & branches</b> press <b>Add country</b> (name, code, currency, rate, tax), then <b>Add branch</b>. Numbering, currency, tax and approvers start working straight away, without code changes.'],
    ['title' => 'Users, roles and permissions', 'keywords' => ['user', 'users', 'role', 'roles', 'permission', 'permissions', 'invite', 'access', 'who can'], 'answer' => '<b>Administration → Users & roles</b> lists everyone with their role, branch and 2FA status. Super Administrators invite users and tick permissions per role in the matrix. Form approval steps follow roles: Accountant, Assistant Manager, Country Manager, Regional Manager, Financial Controller, Finance Manager, CFO, CEO.'],
    ['title' => 'Audit trail', 'keywords' => ['audit', 'audit trail', 'history', 'who changed', 'log', 'track changes'], 'answer' => '<b>Administration → Audit trail</b> records every change with user, time, device, and the previous and new value. Each invoice and form also has its own History panel. Financial records are voided or reversed, never deleted.', 'route' => 'audit.index'],
    ['title' => 'Reports', 'keywords' => ['report', 'reports', 'export a report', 'sales report', 'profit', 'loss', 'cash flow', 'aging', 'receivables report', 'export report'], 'answer' => '<b>Catalogue & records → Reports</b> has financial (sales, receivables aging, P&L, cash flow…), operational (branch and country performance, product sales, staff activity) and audit reports. Filter by period, country and currency; export to PDF, Excel or copy as CSV.', 'route' => 'budget.index'],
    ['title' => 'Payment reminders and messages', 'keywords' => ['reminder', 'reminders', 'overdue reminder', 'communications', 'message history', 'automatic reminders'], 'answer' => '<b>Communications</b> shows every message sent and the automatic reminder rules (7 days before due, on the due date, 3 and 7 days overdue). Switch rules on or off there and edit the wording in Documents → Document templates. You can also send a reminder from any unpaid invoice.', 'route' => 'messages.index'],
    ['title' => 'Document templates and variables', 'keywords' => ['document template', 'templates', 'variables', 'placeholder', 'wording', 'customer_name'], 'answer' => '<b>Documents → Document templates</b> holds the wording for invoices, receipts, statements and reminder messages. Click a variable such as {{customer_name}} to insert it; the preview fills it from a real record so staff never retype data.', 'route' => 'forms.index'],
    ['title' => 'Storing documents', 'keywords' => ['upload document', 'documents', 'contract', 'licence', 'attachment', 'file storage', 'expiry'], 'answer' => '<b>Documents → Repository</b> stores contracts, licences and supporting documents linked to customers, suppliers, expenses, branches or staff, with tags, version and expiry date. Documents expiring within 30 days appear on the Dashboard.', 'route' => 'forms.index'],
    ['title' => 'Notifications', 'keywords' => ['notification', 'notifications', 'bell', 'alerts', 'alert'], 'answer' => 'The bell at the top lists approvals waiting, payments received, overdue invoices, forms returned and expiring documents. Click one to open the record. The Dashboard’s <b>What needs attention today</b> panel summarises the same.'],
    ['title' => 'Security, 2FA and backups', 'keywords' => ['security', '2fa', 'two factor', 'password', 'backup', 'restore', 'session', 'timeout', 'login', 'sign in'], 'answer' => 'Sign-in uses a password plus a 6-digit two-factor code; sessions end after 30 idle minutes. Sensitive actions need a second person’s PIN. Backups run daily at 02:00 with 30 daily and 12 monthly copies; see <b>Settings → Backup</b>.'],
    ['title' => 'Company details and logo on documents', 'keywords' => ['logo', 'company details', 'change the logo', 'logo on documents', 'the logo', 'letterhead', 'bank details', 'organization', 'organisation', 'branding'], 'answer' => '<b>Settings → Organization</b> holds the address, phone, email, tax ID, bank and mobile money details and the logo printed on every invoice, receipt and statement. Legal entity names per country are in <b>Countries & branches</b>.'],
    ['title' => 'Messaging colleagues in other branches and countries', 'keywords' => ['message', 'messages', 'chat', 'team messages', 'message a colleague', 'colleague', 'send a message', 'communicate'], 'answer' => 'Open <b>Team messages</b> and press <b>New message</b> to write to anyone in any branch or country, or pick several people for a group. Each person shows their role, branch and current local time. Attach a finance form or invoice so they can open it in one click, and use <b>@Name</b> to mention someone. From any finance form, <b>Team message</b> starts a message with the form attached.', 'route' => 'messages.index'],
];
