{{-- Invoice layout, shared by the screen, the PDF and the customer share link. Table-based so DomPDF renders it identically. --}}
@php $c = $invoice->customer; $co = $invoice->country; $cur = $invoice->currency_code; $s = $invoice->displayStatus();
  $wm = ['Draft' => 'DRAFT', 'Pending approval' => 'PENDING APPROVAL', 'Cancelled' => 'CANCELLED', 'Paid' => 'PAID'][$s] ?? null; @endphp
<div class="paper">
  @if($wm)<div class="wm {{ $s === 'Paid' ? 'paid' : '' }}">{{ $wm }}</div>@endif
  <table class="p-head" style="width:100%"><tr>
    <td><table><tr><td style="vertical-align:top;padding-right:10px">@include('partials.doc-logos')</td>
      <td><b style="font-size:13px">{{ $co->legal_entity }}</b><br>{{ $co->address ?: $invoice->branch->office.', '.$invoice->branch->name }}, {{ $co->name }}@if($co->phone || $co->email)<br>{{ collect([$co->phone, $co->email])->filter()->implode(' · ') }}@endif @if($co->tax_id)<br>TIN {{ $co->tax_id }}@endif</td></tr></table></td>
    <td class="r"><div class="p-doc">Invoice</div><div class="mono">{{ $invoice->number }}</div>@if($invoice->version > 1)<div class="muted">Revision {{ $invoice->version }}</div>@endif</td>
  </tr></table>
  <div class="line"></div>
  <table style="width:100%;margin-bottom:12px"><tr>
    <td style="width:58%;vertical-align:top"><div class="muted" style="font-size:9px;text-transform:uppercase;letter-spacing:.1em">Bill to</div>
      <b>{{ $c->displayName() }}</b><br>@if($c->company)Attn: {{ $c->name }}<br>@endif{{ $c->address }}, {{ $c->city }}<br>{{ $c->phone }} · {{ $c->email }}@if($c->tax_id)<br>TIN {{ $c->tax_id }}@endif</td>
    <td style="vertical-align:top"><table>
      <tr><td class="muted">Invoice date</td><td class="r fl">{{ fdate($invoice->issue_date) }}</td></tr>
      <tr><td class="muted">Due date</td><td class="r fl">{{ fdate($invoice->due_date) }}</td></tr>
      <tr><td class="muted">Terms</td><td class="r fl">{{ config('dopay.payment_terms')[$c->payment_terms_days] ?? 'Net '.$c->payment_terms_days }}</td></tr>
      <tr><td class="muted">Currency</td><td class="r fl">{{ $cur }}</td></tr>
    </table></td></tr></table>
  <div class="p-tw"><table class="p-items items" style="width:100%"><thead><tr><th>#</th><th>Description</th><th class="r">Qty</th><th class="r">Unit price</th><th class="r">Disc</th><th class="r">{{ $co->tax_name }}</th><th class="r">Amount</th></tr></thead><tbody>
    @foreach($invoice->items as $n => $it)<tr><td>{{ $n + 1 }}</td><td>{{ $it->description }}</td><td class="r">{{ rtrim(rtrim(number_format($it->quantity, 3), '0'), '.') }}</td><td class="r">{{ money($it->unit_price, $cur, false) }}</td><td class="r">{{ (float) $it->discount_pct ? rtrim(rtrim($it->discount_pct, '0'), '.').'%' : '—' }}</td><td class="r">{{ rtrim(rtrim($it->tax_pct, '0'), '.') }}%</td><td class="r">{{ money($it->line_total, $cur, false) }}</td></tr>@endforeach
  </tbody></table></div>
  <table style="width:100%;margin-top:10px"><tr><td style="width:55%"></td><td><table style="width:100%">
    <tr><td>Subtotal</td><td class="r">{{ money($invoice->subtotal, $cur, false) }}</td></tr>
    @if((float) $invoice->discount_total)<tr><td>Discount</td><td class="r">−{{ money($invoice->discount_total, $cur, false) }}</td></tr>@endif
    <tr><td>{{ $co->tax_name }}</td><td class="r">{{ money($invoice->tax_total, $cur, false) }}</td></tr>
    <tr><td class="fl" style="border-top:1px solid #ccc">Total</td><td class="r fl" style="border-top:1px solid #ccc">{{ money($invoice->total, $cur) }}</td></tr>
    <tr><td>Amount paid</td><td class="r">{{ money($invoice->amount_paid, $cur, false) }}</td></tr>
    <tr><td class="due" style="padding:4px 6px">Balance due</td><td class="r due" style="padding:4px 6px">{{ money($invoice->balance(), $cur) }}</td></tr>
  </table></td></tr></table>
  <table style="width:100%;margin-top:16px;font-size:10.5px;color:#444"><tr>
    <td style="width:50%;vertical-align:top;padding-right:12px"><b style="font-size:9px;text-transform:uppercase;letter-spacing:.1em">Payment</b><br>{!! nl2br(e($invoice->notes ?: 'Please quote '.$invoice->number.' with your payment.')) !!}@if($co->bank_details)<br>Bank: {{ $co->bank_details }}@endif @if($co->mobile_money)<br>Mobile money: {{ $co->mobile_money }}@endif</td>
    <td style="vertical-align:top"><b style="font-size:9px;text-transform:uppercase;letter-spacing:.1em">Terms &amp; conditions</b><br>{!! nl2br(e($invoice->terms ?: 'Payment is due by the date shown. Goods remain the property of the seller until paid in full.')) !!}</td>
  </tr></table>
  <div class="p-foot" style="margin-top:18px;border-top:1px solid #E3E8F0;padding-top:8px;font-size:9.5px;color:#777">
    @if($invoice->shareUrl() && $invoice->generated_at)Verify online: {{ $invoice->shareUrl() }} · @endif Generated by Dopay CRM @if($invoice->approver) · Approved by {{ $invoice->approver->name }}@endif
  </div>
</div>
